#pragma once

enum EMeshRenderLayerType
{
	RENDERLAYER_OPAQUE = 0,
	RENDERLAYER_TRANSPARENT,
	RENDERLAYER_ALPHATEST,
	RENDERLAYER_BACKGROUND,
	RENDERLAYER_OPAQUE_REFLECTOR = 4,
	RENDERLAYER_SHADOW_RENDER = 8,
	RENDERLAYER_SELECT = 9,
	RENDERLAYER_OPERATION_HANDLE = 10,
	RENDERLAYER_OPERATION_HANDLE_ROT_PLANE = 11,
	RENDERLAYER_NORMAL = 20,
	RENDERLAYER_SSAO = 21,
	RENDERLAYER_SSAO_BILATERAL_BLUR = 22,
};