#pragma once

enum EMeshRenderLayerType
{
	RENDERLAYER_OPAQUE = 0,
	RENDERLAYER_TRANSPARENT,
	RENDERLAYER_ALPHATEST,
	RENDERLAYER_BACKGROUND,
	RENDERLAYER_OPAQUE_REFLECTOR = 4,
	RENDERLAYER_SHADOW_RENDER = 8,
};