#include "Input.h"

FCaptureOnMousesWheelsDelegate MousesWheelsDelegate;
FCaptureOnMousesDelegate LMouseDownDelegate;
FCaptureOnMousesDelegate MouseDownDelegate;
FCaptureOnMousesDelegate MouseUpDelegate;
FCaptureOnMousesDelegate MouseMoveDelegate;