#pragma once

#define CODE_REFLECTOR_MACRO_INNER(A,B,C,D) A##B##C##D
#define CODE_REFLECTOR_MACRO(A,B,C,D) CODE_REFLECTOR_MACRO_INNER(A,B,C,D)

#define CVARIABLE(...) 
#define CDIAPER(...) 
#define CODEREFLECTION(...) \
CODE_REFLECTOR_MACRO(CURRENT_FILE_ID_BT,_,NewLine,_GENERATED_BODY_BT)